# Searching a Website's API, and exploring the output JSON

In [1]:
import pandas as pd #pandas does html!
s_p_tables= pd.read_html('https://en.wikipedia.org/wiki/List_of_S%26P_500_companies')
s_p_tables #raw data

[    Symbol                         Security SEC filings  \
 0      MMM                       3M Company     reports
 1      ABT              Abbott Laboratories     reports
 2     ABBV                      AbbVie Inc.     reports
 3     ABMD                      ABIOMED Inc     reports
 4      ACN                    Accenture plc     reports
 5     ATVI              Activision Blizzard     reports
 6     ADBE                       Adobe Inc.     reports
 7      AMD       Advanced Micro Devices Inc     reports
 8      AAP               Advance Auto Parts     reports
 9      AES                         AES Corp     reports
 10     AFL                        AFLAC Inc     reports
 11       A         Agilent Technologies Inc     reports
 12     APD     Air Products & Chemicals Inc     reports
 13    AKAM          Akamai Technologies Inc     reports
 14     ALK             Alaska Air Group Inc     reports
 15     ALB                   Albemarle Corp     reports
 16     ARE  Alexandria Real Estate Equities     reports
 17    ALXN          Alexion Pharmaceuticals     reports
 18    ALGN                 Align Technology     reports
 19    ALLE                         Allegion     reports
 20     AGN                    Allergan, plc     reports
 21     ADS            Alliance Data Systems     reports
 22     LNT              Alliant Energy Corp     reports
 23     ALL                    Allstate Corp     reports
 24   GOOGL             Alphabet Inc Class A     reports
 25    GOOG             Alphabet Inc Class C     reports
 26      MO                 Altria Group Inc     reports
 27    AMZN                  Amazon.com Inc.     reports
 28    AMCR                        Amcor plc     reports
 29     AEE                      Ameren Corp     reports
 ..     ...                              ...         ...
 475      V                        Visa Inc.     reports
 476    VNO             Vornado Realty Trust     reports
 477    VMC                 Vulcan Materials     reports
 478    WRB        W. R. Berkley Corporation     reports
 479    WAB               Wabtec Corporation     reports
 480    WMT                          Walmart     reports
 481    WBA         Walgreens Boots Alliance     reports
 482    DIS          The Walt Disney Company     reports
 483     WM            Waste Management Inc.     reports
 484    WAT               Waters Corporation     reports
 485    WEC             Wec Energy Group Inc     reports
 486    WFC                      Wells Fargo     reports
 487   WELL                   Welltower Inc.     reports
 488    WDC                  Western Digital     reports
 489     WU                 Western Union Co     reports
 490    WRK                         WestRock     reports
 491     WY                     Weyerhaeuser     reports
 492    WHR                  Whirlpool Corp.     reports
 493    WMB                    Williams Cos.     reports
 494   WLTW             Willis Towers Watson     reports
 495   WYNN                 Wynn Resorts Ltd     reports
 496    XEL                  Xcel Energy Inc     reports
 497    XRX                            Xerox     reports
 498   XLNX                           Xilinx     reports
 499    XYL                       Xylem Inc.     reports
 500    YUM                  Yum! Brands Inc     reports
 501   ZBRA               Zebra Technologies     reports
 502    ZBH           Zimmer Biomet Holdings     reports
 503   ZION                    Zions Bancorp     reports
 504    ZTS                           Zoetis     reports

                 GICS Sector                             GICS Sub Industry  \
 0               Industrials                      Industrial Conglomerates
 1               Health Care                         Health Care Equipment
 2               Health Care                               Pharmaceuticals
 3               Health Care                         Health Care Equipment
 4    Information Technology                IT Consulting & Other Services
 5    Communication Services                Interactive Home Entertainment
 6    Information Technology                          Application Software
 7    Information Technology                                Semiconductors
 8    Consumer Discretionary                             Automotive Retail
 9                 Utilities  Independent Power Producers & Energy Traders
 10               Financials                       Life & Health Insurance
 11              Health Care                         Health Care Equipment
 12                Materials                              Industrial Gases
 13   Information Technology            Internet Services & Infrastructure
 14              Industrials                                      Airlines
 15                Materials                           Specialty Chemicals
 16              Real Estate                                  Office REITs
 17              Health Care                                 Biotechnology
 18              Health Care                          Health Care Supplies
 19              Industrials                             Building Products
 20              Health Care                               Pharmaceuticals
 21   Information Technology         Data Processing & Outsourced Services
 22                Utilities                            Electric Utilities
 23               Financials                 Property & Casualty Insurance
 24   Communication Services                  Interactive Media & Services
 25   Communication Services                  Interactive Media & Services
 26         Consumer Staples                                       Tobacco
 27   Consumer Discretionary            Internet & Direct Marketing Retail
 28                Materials                               Paper Packaging
 29                Utilities                               Multi-Utilities
 ..                      ...                                           ...
 475  Information Technology         Data Processing & Outsourced Services
 476             Real Estate                                  Office REITs
 477               Materials                        Construction Materials
 478              Financials                 Property & Casualty Insurance
 479             Industrials         Construction Machinery & Heavy Trucks
 480        Consumer Staples                  Hypermarkets & Super Centers
 481        Consumer Staples                                   Drug Retail
 482  Communication Services                        Movies & Entertainment
 483             Industrials           Environmental & Facilities Services
 484             Health Care                      Health Care Distributors
 485               Utilities                            Electric Utilities
 486              Financials                             Diversified Banks
 487             Real Estate                             Health Care REITs
 488  Information Technology    Technology Hardware, Storage & Peripherals
 489  Information Technology         Data Processing & Outsourced Services
 490               Materials                               Paper Packaging
 491             Real Estate                             Specialized REITs
 492  Consumer Discretionary                          Household Appliances
 493                  Energy            Oil & Gas Storage & Transportation
 494              Financials                             Insurance Brokers
 495  Consumer Discretionary                              Casinos & Gaming
 496               Utilities                               Multi-Utilities
 497  Information Technology    Technology Hardware, Storage & Peripherals
 498  Information Technology                                Semiconductors
 499             Industrials                          Industrial Machinery
 500  Consumer Discretionary                                   Restaurants
 501  Information Technology            Electronic Equipment & Instruments
 502             Health Care                         Health Care Equipment
 503              Financials                                Regional Banks
 504             Health Care                               Pharmaceuticals

                 Headquarters Location Date first added      CIK      Founded
 0                 St. Paul, Minnesota              NaN    66740         1902
 1             North Chicago, Illinois       1964-03-31     1800         1888
 2             North Chicago, Illinois       2012-12-31  1551152  2013 (1888)
 3              Danvers, Massachusetts       2018-05-31   815094         1981
 4                     Dublin, Ireland       2011-07-06  1467373         1989
 5            Santa Monica, California       2015-08-31   718877         2008
 6                San Jose, California       1997-05-05   796343         1982
 7             Santa Clara, California       2017-03-20     2488         1969
 8             Raleigh, North Carolina       2015-07-09  1158449         1932
 9                 Arlington, Virginia       1998-10-02   874761         1981
 10                  Columbus, Georgia       1999-05-28     4977         1955
 11            Santa Clara, California       2000-06-05  1090872         1999
 12            Allentown, Pennsylvania       1985-04-30     2969         1940
 13           Cambridge, Massachusetts       2007-07-12  1086222         1998
 14                Seattle, Washington       2016-05-13   766421         1985
 15          Charlotte, North Carolina       2016-07-01   915913         1994
 16               Pasadena, California       2017-03-20  1035443         1994
 17              Boston, Massachusetts       2012-05-25   899866         1992
 18               San Jose, California       2017-06-19  1097149         1997
 19                    Dublin, Ireland       2013-12-02  1579241         1908
 20                    Dublin, Ireland       1999-04-12  1578845         1983
 21                       Plano, Texas       2013-12-23  1101215         1996
 22                 Madison, Wisconsin       2016-07-01   352541         1917
 23      Northfield Township, Illinois       1995-07-13   899051         1931
 24          Mountain View, California       2014-04-03  1652044         1998
 25          Mountain View, California       2006-04-03  1652044         1998
 26                 Richmond, Virginia              NaN   764180         1985
 27                Seattle, Washington       2005-11-18  1018724         1994
 28   Warmley, Bristol, United Kingdom       2019-06-07  1748790  2019 (1860)
 29                St. Louis, Missouri       1991-09-19  1002910         1902
 ..                                ...              ...      ...          ...
 475         San Francisco, California       2009-12-21  1403161          NaN
 476                New York, New York              NaN   899689          NaN
 477               Birmingham, Alabama       1999-06-30  1396009          NaN
 478            Greenwich, Connecticut       2019-12-05    11544         1967
 479          Wilmerding, Pennsylvania       2019-02-27   943452  1999 (1869)
 480             Bentonville, Arkansas       1982-08-31   104169          NaN
 481               Deerfield, Illinois       1979-12-31  1618921         2014
 482               Burbank, California       1976-06-30  1001039          NaN
 483                    Houston, Texas              NaN   823768         1968
 484            Milford, Massachusetts              NaN  1000697         1958
 485              Milwaukee, Wisconsin       2008-10-31   783325          NaN
 486         San Francisco, California       1976-06-30    72971          NaN
 487                      Toledo, Ohio       2009-01-30   766704          NaN
 488                Irvine, California       2009-07-01   106040          NaN
 489               Englewood, Colorado              NaN  1365135         1851
 490                Richmond, Virginia              NaN  1636023         2015
 491           Federal Way, Washington              NaN   106535          NaN
 492           Benton Harbor, Michigan              NaN   106640         1911
 493                   Tulsa, Oklahoma       1975-03-31   107263          NaN
 494            London, United Kingdom       2016-01-05  1140536          NaN
 495                  Paradise, Nevada       2008-11-14  1174922          NaN
 496            Minneapolis, Minnesota              NaN    72903         1909
 497              Norwalk, Connecticut              NaN   108772         1906
 498              San Jose, California       1999-11-08   743988          NaN
 499            White Plains, New York       2011-11-01  1524472          NaN
 500              Louisville, Kentucky       1997-10-06  1041061          NaN
 501            Lincolnshire, Illinois       2019-12-23   877212         1969
 502                   Warsaw, Indiana       2001-08-07  1136869          NaN
 503              Salt Lake City, Utah       2001-06-22   109380          NaN
 504          Florham Park, New Jersey       2013-06-21  1555280          NaN

 [505 rows x 9 columns],
                    Date  Added                                Removed  \
                    Date Ticker                       Security  Ticker
 0      January 28, 2020   PAYC                         Paycom     WCG
 1     December 23, 2019    LYV      Live Nation Entertainment     AMG
 2     December 23, 2019   ZBRA             Zebra Technologies    TRIP
 3     December 23, 2019    STE                     STERIS plc     MAC
 4      December 9, 2019   ODFL      Old Dominion Freight Line     STI
 5      December 5, 2019    WRB      W. R. Berkley Corporation    VIAB
 6     November 21, 2019    NOW                     ServiceNow    CELG
 7       October 3, 2019    LVS                Las Vegas Sands    NKTR
 8    September 26, 2019    NVR                        NVR Inc     JEF
 9    September 23, 2019    CDW                            CDW     TSS
 10       August 9, 2019   LDOS                Leidos Holdings     APC
 11       August 9, 2019    IEX               IDEX Corporation      FL
 12        July 15, 2019   TMUS                    T-Mobile US     RHT
 13         July 1, 2019   MKTX                    MarketAxess     LLL
 14         June 7, 2019    BMS                   Bemis Co Inc     MAT
 15         June 3, 2019   CTVA                        Corteva     FLR
 16        April 2, 2019    DOW                       Dow Inc.     BHF
 17    February 27, 2019    WAB             Wabtec Corporation      GT
 18    February 15, 2019    ATO              Atmos Energy Corp     NFX
 19     January 18, 2019    TFX                       Teleflex     PCG
 20      January 2, 2019    FRC            First Republic Bank     SCG
 21    December 24, 2018     CE                       Celanese    ESRX
 22     December 3, 2018     LW       Lamb Weston Holdings Inc     COL
 23     December 3, 2018   MXIM  Maxim Integrated Products Inc     AET
 24     December 3, 2018   FANG             Diamondback Energy    SRCL
 25    November 13, 2018   JKHY        Jack Henry & Associates     EQT
 26     November 6, 2018   KEYS          Keysight Technologies      CA
 27     October 11, 2018   FTNT                       Fortinet    EVHC
 28      October 1, 2018    ROL                   Rollins Inc.    ANDV
 29   September 14, 2018    WCG                       WellCare      XL
 ..                  ...    ...                            ...     ...
 199   December 17, 2010   FFIV               F5 Networks Inc.      EK
 200   December 17, 2010   NFLX                   Netflix Inc.     ODP
 201   December 17, 2010    NFX           Newfield Exploration     NYT
 202     August 26, 2010    TYC        Tyco International Ltd.     SII
 203       July 14, 2010     CB                  Chubb Limited     MIL
 204       June 30, 2010    QEP                  QEP Resources     STR
 205       June 28, 2010    KMX                   CarMax, Inc.     XTO
 206      April 29, 2010   CERN                   Cerner Corp.     BJS
 207   February 26, 2010     HP              Helmerich & Payne      RX
 208    November 3, 2009   PCLN                  Priceline.com     SGP
 209  September 28, 2009    ARG                     Airgas Inc     CBE
 210       March 3, 2009    HRL                   Hormel Foods    ACAS
 211       March 3, 2009    VTR                    Ventas Inc.     JNY
 212   December 31, 2008     OI                 Owens-Illinois      WB
 213  September 12, 2008    CRM                 Salesforce.com     FRE
 214  September 12, 2008   FAST                       Fastenal     FNM
 215       June 10, 2008     LO                 Lorillard Inc.     ABK
 216   December 20, 2007    RRC                Range Resources     TRB
 217   December 13, 2007    GME                       GameStop      DJ
 218    October 26, 2007    JEC       Jacobs Engineering Group      AV
 219     August 24, 2007    LUK              Leucadia National     KSE
 220      March 30, 2007    KFT                    Kraft Foods     TSG
 221    January 10, 2007    AVB    AvalonBay Communities, Inc.     SBL
 222        July 1, 2005    STZ           Constellation Brands     GLK
 223  September 25, 2003   ESRX                Express Scripts    QTRN
 224    December 5, 2000   INTU                         Intuit      BS
 225    December 5, 2000    SBL            Symbol Technologies      OI
 226    December 5, 2000    AYE               Allegheny Energy     GRA
 227    December 5, 2000    ABK                Ambac Financial     CCK
 228       July 27, 2000   JDSU                   JDS Uniphase     RAD

                                          \
                                Security
 0                              WellCare
 1             Affiliated Managers Group
 2                           TripAdvisor
 3                              Macerich
 4                        SunTrust Banks
 5                                Viacom
 6                               Celgene
 7                   Nektar Therapeutics
 8         Jefferies Financial Group Inc
 9                                  TSYS
 10                   Anadarko Petroleum
 11                          Foot Locker
 12                              Red Hat
 13                      L3 Technologies
 14                           Mattel Inc
 15                    Fluor Corporation
 16                Brighthouse Financial
 17   The Goodyear Tire & Rubber Company
 18                 Newfield Exploration
 19                            PG&E Corp
 20                                SCANA
 21                      Express Scripts
 22                     Rockwell Collins
 23                            Aetna Inc
 24                           Stericycle
 25                             EQT Corp
 26                              CA Inc.
 27                  Envision Healthcare
 28                             Andeavor
 29                             XL Group
 ..                                  ...
 199                   Eastman Kodak Co.
 200                   Office Depot Inc.
 201              The New York Times Co.
 202            Smith International Inc.
 203                      Millipore Inc.
 204                       Questar Corp.
 205                     XTO Energy Inc.
 206                 BJ Services Company
 207                          IMS Health
 208               Schering-Plough Corp.
 209              Cooper Industries Ltd.
 210                    American Capital
 211                 Jones Apparel Group
 212                       Wachovia Bank
 213                         Freddie Mac
 214                          Fannie Mae
 215                     Ambac Financial
 216                         Tribune Co.
 217                           Dow Jones
 218                          Avaya Inc.
 219                             KeySpan
 220                      Sabre Holdings
 221                 Symbol Technologies
 222                Great Lakes Chemical
 223             Quintiles Transnational
 224                     Bethlehem Steel
 225                      Owens-Illinois

In [2]:
constituents = s_p_tables[0] #it will download all tables on the page to a "list of dataframes"
constituents #no URLs, just raw text

,Symbol,Security,SEC filings,GICS Sector,GICS Sub Industry,Headquarters Location,Date first added,CIK,Founded
0,MMM,3M Company,reports,Industrials,Industrial Conglomerates,"St. Paul, Minnesota",NaN,66740,1902
1,ABT,Abbott Laboratories,reports,Health Care,Health Care Equipment,"North Chicago, Illinois",1964-03-31,1800,1888
2,ABBV,AbbVie Inc.,reports,Health Care,Pharmaceuticals,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
3,ABMD,ABIOMED Inc,reports,Health Care,Health Care Equipment,"Danvers, Massachusetts",2018-05-31,815094,1981
4,ACN,Accenture plc,reports,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989
5,ATVI,Activision Blizzard,reports,Communication Services,Interactive Home Entertainment,"Santa Monica, California",2015-08-31,718877,2008
6,ADBE,Adobe Inc.,reports,Information Technology,Application Software,"San Jose, California",1997-05-05,796343,1982
7,AMD,Advanced Micro Devices Inc,reports,Information Technology,Semiconductors,"Santa Clara, California",2017-03-20,2488,1969
8,AAP,Advance Auto Parts,reports,Consumer Discretionary,Automotive Retail,"Raleigh, North Carolina",2015-07-09,1158449,1932
9,AES,AES Corp,reports,Utilities,Independent Power Producers & Energy Traders,"Arlington, Virginia",1998-10-02,874761,1981
10,AFL,AFLAC Inc,reports,Financials,Life & Health Insurance,"Columbus, Georgia",1999-05-28,4977,1955
11,A,Agilent Technologies Inc,reports,Health Care,Health Care Equipment,"Santa Clara, California",2000-06-05,1090872,1999
12,APD,Air Products & Chemicals Inc,reports,Materials,Industrial Gases,"Allentown, Pennsylvania",1985-04-30,2969,1940
13,AKAM,Akamai Technologies Inc,reports,Information Technology,Internet Services & Infrastructure,"Cambridge, Massachusetts",2007-07-12,1086222,1998
14,ALK,Alaska Air Group Inc,reports,Industrials,Airlines,"Seattle, Washington",2016-05-13,766421,1985
15,ALB,Albemarle Corp,reports,Materials,Specialty Chemicals,"Charlotte, North Carolina",2016-07-01,915913,1994
16,ARE,Alexandria Real Estate Equities,reports,Real Estate,Office REITs,"Pasadena, California",2017-03-20,1035443,1994
17,ALXN,Alexion Pharmaceuticals,reports,Health Care,Biotechnology,"Boston, Massachusetts",2012-05-25,899866,1992
18,ALGN,Align Technology,reports,Health Care,Health Care Supplies,"San Jose, California",2017-06-19,1097149,1997
19,ALLE,Allegion,reports,Industrials,Building Products,"Dublin, Ireland",2013-12-02,1579241,1908
20,AGN,"Allergan, plc",reports,Health Care,Pharmaceuticals,"Dublin, Ireland",1999-04-12,1578845,1983
21,ADS,Alliance Data Systems,reports,Information Technology,Data Processing & Outsourced Services,"Plano, Texas",2013-12-23,1101215,1996
22,LNT,Alliant Energy Corp,reports,Utilities,Electric Utilities,"Madison, Wisconsin",2016-07-01,352541,1917
23,ALL,Allstate Corp,reports,Financials,Property & Casualty Insurance,"Northfield Township, Illinois",1995-07-13,899051,1931
24,GOOGL,Alphabet Inc Class A,reports,Communication Services,Interactive Media & Services,"Mountain View, California",2014-04-03,1652044,1998
25,GOOG,Alphabet Inc Class C,reports,Communication Services,Interactive Media & Services,"Mountain View, California",2006-04-03,1652044,1998
26,MO,Altria Group Inc,reports,Consumer Staples,Tobacco,"Richmond, Virginia",NaN,764180,1985
27,AMZN,Amazon.com Inc.,reports,Consumer Discretionary,Internet & Direct Marketing Retail,"Seattle, Washington",2005-11-18,1018724,1994
28,AMCR,Amcor plc,reports,Materials,Paper Packaging,"Warmley, Bristol, United Kingdom",2019-06-07,1748790,2019 (1860)
29,AEE,Ameren Corp,reports,Utilities,Multi-Utilities,"St. Louis, Missouri",1991-09-19,1002910,1902
...,...,...,...,...,...,...,...,...,...
475,V,Visa Inc.,reports,Information Technology,Data Processing & Outsourced Services,"San Francisco, California",2009-12-21,1403161,NaN
476,VNO,Vornado Realty Trust,reports,Real Estate,Office REITs,"New York, New York",NaN,899689,NaN
477,VMC,Vulcan Materials,reports,Materials,Construction Materials,"Birmingham, Alabama",1999-06-30,1396009,NaN
478,WRB,W. R. Berkley Corporation,reports,Financials,Property & Casualty Insurance,"Greenwich, Connecticut",2019-12-05,11544,1967
479,WAB,Wabtec Corporation,reports,Industrials,Construction Machinery & Heavy Trucks,"Wilmerding, Pennsylvania",2019-02-27,943452,1999 (1869)
480,WMT,Walmart,reports,Consumer Staples,Hypermarkets & Super Centers,"Bentonville, Arkansas",1982-08-31,104169,NaN
481,WBA,Walgreens Boots Alliance,reports,Consumer Staples,Drug Retail,"Deerfield, Illinois",1979-12-31,1618921,2014
482,DIS,The Walt Disney Company,reports,Communication Services,Movies & Entertainment,"Burbank, California",1976-06-30,1001039,NaN
483,WM,Waste Management Inc.,reports,Industrials,Environmental & Facilities Services,"Houston, Texas",NaN,823768,1968
484,WAT,Waters Corporation,reports,Health Care,Health Care Distributors,"Milford, Massachusetts",NaN,1000697,1958
485,WEC,Wec Energy Group Inc,reports,Utilities,Electric Utilities,"Milwaukee, Wisconsin",2008-10-31,783325,NaN
486,WFC,Wells Fargo,reports,Financials,Diversified Banks,"San Francisco, California",1976-06-30,72971,NaN
487,WELL,Welltower Inc.,reports,Real Estate,Health Care REITs,"Toledo, Ohio",2009-01-30,766704,NaN
488,WDC,Western Digital,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Irvine, California",2009-07-01,106040,NaN
489,WU,Western Union Co,reports,Information Technology,Data Processing & Outsourced Services,"Englewood, Colorado",NaN,1365135,1851
490,WRK,WestRock,reports,Materials,Paper Packaging,"Richmond, Virginia",NaN,1636023,2015
491,WY,Weyerhaeuser,reports,Real Estate,Specialized REITs,"Federal Way, Washington",NaN,106535,NaN
492,WHR,Whirlpool Corp.,reports,Consumer Discretionary,Household Appliances,"Benton Harbor, Michigan",NaN,106640,1911
493,WMB,Williams Cos.,reports,Energy,Oil & Gas Storage & Transportation,"Tulsa, Oklahoma",1975-03-31,107263,NaN
494,WLTW,Willis Towers Watson,reports,Financials,Insurance Brokers,"London, United Kingdom",2016-01-05,1140536,NaN
495,WYNN,Wynn Resorts Ltd,reports,Consumer Discretionary,Casinos & Gaming,"Paradise, Nevada",2008-11-14,1174922,NaN
496,XEL,Xcel Energy Inc,reports,Utilities,Multi-Utilities,"Minneapolis, Minnesota",NaN,72903,1909
497,XRX,Xerox,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Norwalk, Connecticut",NaN,108772,1906
498,XLNX,Xilinx,reports,Information Technology,Semiconductors,"San Jose, California",1999-11-08,743988,NaN
499,XYL,Xylem Inc.,reports,Industrials,Industrial Machinery,"White Plains, New York",2011-11-01,1524472,NaN
500,YUM,Yum! Brands Inc,reports,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,NaN
501,ZBRA,Zebra Technologies,reports,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
502,ZBH,Zimmer Biomet Holdings,reports,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,NaN
503,ZION,Zions Bancorp,reports,Financials,Regional Banks,"Salt Lake City, Utah",2001-06-22,109380,NaN
504,ZTS,Zoetis,reports,Health Care,Pharmaceuticals,"Florham Park, New Jersey",2013-06-21,1555280,NaN

In [8]:
import requests
base_url = 'https://chroniclingamerica.loc.gov/search/pages/results/'
parameters = '?andtext=lynching&format=json'

url = base_url + parameters
print(url)
r = requests.get(base_url + parameters ) #runs the search, but shows ugly raw text

https://chroniclingamerica.loc.gov/search/pages/results/?andtext=lynching&format=json

In [4]:
r
r.json() #json is a dictionary
r.status_code #200 is a good result!

200

In [9]:
search_json = r.json() #extracting the json
search_json['totalItems'] #access element like in pandas
search_json.keys() #get a list of the keys ("elements"?)

dict_keys(['totalItems', 'endIndex', 'startIndex', 'itemsPerPage', 'items'])

In [10]:
len(search_json['items']) #20 items/ 20 articles on the page 
                            #items is a list of items
search_json['items'][0].keys() #tells you what is in the first 'item'/article
                            #works on each item
search_json['items'][0]['title'] #tells you the title

'Dearborn independent. [volume]'

In [11]:
# pandas can IMPORT JSON INTO A DATAFRAME
pd.DataFrame(search_json['items'])

,alt_title,batch,city,country,county,date,edition,edition_label,end_year,frequency,...,publisher,section_label,sequence,start_year,state,subject,title,title_normal,type,url
0,[],mimtptc_jackson_ver01,[Dearborn],Michigan,[Wayne],19211022,None,,1927,Weekly,...,Suburban Pub. Co.,,1,1901,[Michigan],"[Dearborn (Mich.)--Newspapers., Michigan--Dear...",Dearborn independent. [volume],dearborn independent.,page,https://chroniclingamerica.loc.gov/lccn/201321...
1,[],iune_hotel_ver01,[Chicago],Illinois,[Cook County],19150818,None,LAST EDITION,1917,Daily (except Sunday and holidays),...,N.D. Cochran,,4,1911,[Illinois],"[Chicago (Ill.)--Newspapers., Illinois--Chicag...",The day book. [volume],day book.,page,https://chroniclingamerica.loc.gov/lccn/sn8304...
2,[],msar_iron_ver01,[Jackson],Mississippi,[Hinds],19470614,None,,9999,Weekly,...,P. Greene,,4,1939,[Mississippi],"[African Americans--Mississippi--Newspapers., ...",Jackson advocate. [volume],jackson advocate.,page,https://chroniclingamerica.loc.gov/lccn/sn7900...
3,"[Star, Sunday star]",dlc_dalek_ver01,[Washington],District of Columbia,[None],19221123,None,,1972,Daily,...,W.D. Wallach & Hope,,34,1854,[District of Columbia],"[Washington (D.C.)--fast--(OCoLC)fst01204505, ...",Evening star. [volume],evening star.,page,https://chroniclingamerica.loc.gov/lccn/sn8304...
4,[],wa_elm_ver01,[Seattle],Washington,[King],19180608,None,,1921,Weekly,...,H.R. Cayton,,4,1916,[Washington],[African Americans--Washington (State)--Seattl...,Cayton's weekly.,cayton's weekly.,page,https://chroniclingamerica.loc.gov/lccn/sn8709...
5,[],iune_delta_ver01,[Chicago],Illinois,[Cook County],19130507,None,,1917,Daily (except Sunday and holidays),...,N.D. Cochran,,12,1911,[Illinois],"[Chicago (Ill.)--Newspapers., Illinois--Chicag...",The day book. [volume],day book.,page,https://chroniclingamerica.loc.gov/lccn/sn8304...
6,"[Star, Sunday star]",dlc_2nevelson_ver01,[Washington],District of Columbia,[None],19520210,None,,1972,Daily,...,W.D. Wallach & Hope,,123,1854,[District of Columbia],"[Washington (D.C.)--fast--(OCoLC)fst01204505, ...",Evening star. [volume],evening star.,page,https://chroniclingamerica.loc.gov/lccn/sn8304...
7,[],scu_garydavis_ver01,[Newberry],South Carolina,[Newberry],19041018,None,,1937,Weekly,...,E.H. Aull,,2,1903,[South Carolina],"[Newberry County (S.C.)--Newspapers., South Ca...",The herald and news. [volume],herald and news.,page,https://chroniclingamerica.loc.gov/lccn/sn8606...
8,"[Evening star, Star]",fu_criser_ver02,[Ocala],Florida,[Marion],19200323,None,,1943,Daily (except Sunday),...,Porter & Harding,,2,1895,[Florida],[Florida--Marion County.--fast--(OCoLC)fst0120...,The Ocala evening star. [volume],ocala evening star.,page,https://chroniclingamerica.loc.gov/lccn/sn8402...
9,[New Britain daily herald],ct_floyd_ver01,[New Britain],Connecticut,[Hartford],19260326,None,,1976,Daily (except Sun.),...,Herald Pub. Co.,Second Section,26,1890,[Connecticut],[Connecticut--Hartford County.--fast--(OCoLC)f...,New Britain herald. [volume],new britain herald.,page,https://chroniclingamerica.loc.gov/lccn/sn8201...
10,[],iune_echo_ver01,[Chicago],Illinois,[Cook County],19120909,None,,1917,Daily (except Sunday and holidays),...,N.D. Cochran,,4,1911,[Illinois],"[Chicago (Ill.)--Newspapers., Illinois--Chicag...",The day book. [volume],day book.,page,https://chroniclingamerica.loc.gov/lccn/sn8304...
11,"[Star, Sunday star]",dlc_1duchamp_ver01,[Washington],District of Columbia,[None],19331130,None,,1972,Daily,...,W.D. Wallach & Hope,,5,1854,[District of Columbia],"[Washington (D.C.)--fast--(OCoLC)fst01204505, ...",Evening star. [volume],evening star.,page,https://chroniclingamerica.loc.gov/lccn/sn8304...
12,[],mimtptc_jackson_ver01,[Dearborn],Michigan,[Wayne],19211022,None,,1927,Weekly,...,Suburban Pub. Co.,,12,1901,[Michigan],"[Dearborn (Mich.)--Newspapers., Michigan--Dear...",Dearborn independent. [volume],dearborn independent.,page,https://chroniclingamerica.loc.gov/lccn/201321...
13,[],iune_delta_ver01,[Chicago],Illinois,[Cook County],19131014,None,,1917,Daily (except Sunday and holidays),...,N.D. Cochran,,13,1911,[Illinois],"[Chicago (Ill.)--Newspapers., Illinois--Chicag...",The day book. [volume],day book.,page,https://chroniclingamerica.loc.gov/lccn/sn8304...
14,[],iune_golf_ver01,[Chicago],Illinois,[Cook County],19141013,None,LAST EDITION,1917,Daily (except Sunday and holidays),...,N.D. Cochran,,27,1911,[Illinois],"[Chicago (Ill.)--Newspapers., Illinois--Chicag...",The day book. [volume],day book.,page,https://chroniclingamerica.loc.gov/lccn/sn8304...
15,[],msar_lapis_ver01,[Durant],Mississippi,[Holmes],19480311,None,,1985,Weekly,...,John Kyllingstad & M.J. Peters,,2,1882,[Mississippi],[],The Durant news.,durant news.,page,https://chroniclingamerica.loc.gov/lccn/sn8706...
16,[],az_dyingcowboy_ver01,[Phoenix],Arizona,[Maricopa],19370514,None,,1939,Weekly,...,W.C. Hackett,,1,1929,[Arizona],"[African Americans--Newspapers., African Ameri...",The Arizona gleam. [volume],arizona gleam.,page,https://chroniclingamerica.loc.gov/lccn/sn9506...
17,[],in_jillette_ver01,[Indianapolis],Indiana,[Marion],19341109,None,Home Edition,1965,Daily,...,Indianapolis Daily Times Co.,,9,1922,[Indiana],[Indiana--Indianapolis.--fast--(OCoLC)fst01205...,The Indianapolis times. [volume],indianapolis times.,page,https://chroniclingamerica.loc.gov/lccn/sn8201...
18,[National Afro-American newspaper],mnhi_funkley_ver02,"[Chicago, Minneapolis, Saint Paul]",Minnesota,"[Cook, Hennepin, Ramsey]",19221202,None,,1999,Weekly,...,Northwestern Pub. Co.,,2,1889,"[Illinois, Minnesota, Minnesota]","[African American newspapers--Illinois., Afric...",The Appeal. [volume],appeal.,page,https://chroniclingamerica.loc.gov/lccn/sn8301...
19,[],ohi_amaryllis_ver01,[Dayton],Ohio,[Montgomery],19480121,None,,1950,Daily (except Sun.),...,Paige H. Strickland,,2,1946,[Ohio],"[African Americans--Ohio--Dayton--Newspapers.,...",The Ohio daily-express.,ohio daily-express.,page,https://chroniclingamerica.loc.gov/lccn/sn8807...

In [15]:
#CLASS ACTIVITY - RUN YOUR OWN SEARCH 

base_url = 'https://chroniclingamerica.loc.gov/search/pages/results/'
parameters = '?andtext=arson&format=json'

url = base_url + parameters
print(url)
r = requests.get(base_url + parameters ) #runs the search, but shows ugly raw text

https://chroniclingamerica.loc.gov/search/pages/results/?andtext=arson&format=json

In [21]:
r
r.json() #json is a dictionary
r.status_code

200

In [22]:
search_json = r.json()
search_json['totalItems']
search_json.keys()

dict_keys(['totalItems', 'endIndex', 'startIndex', 'itemsPerPage', 'items'])

In [18]:
len(search_json['items'])

20

In [19]:
search_json['items'][0]['title'] #tells you the title

'The day book. [volume]'

In [23]:
r.url

'https://chroniclingamerica.loc.gov/search/pages/results/?andtext=arson&format=json'

In [24]:
pd.DataFrame(search_json['items'])

,alt_title,batch,city,country,county,date,edition,edition_label,end_year,frequency,...,publisher,section_label,sequence,start_year,state,subject,title,title_normal,type,url
0,[],iune_hotel_ver01,[Chicago],Illinois,[Cook County],19151006,None,LAST EDITION,1917,Daily (except Sunday and holidays),...,N.D. Cochran,,1,1911,[Illinois],"[Chicago (Ill.)--Newspapers., Illinois--Chicag...",The day book. [volume],day book.,page,https://chroniclingamerica.loc.gov/lccn/sn8304...
1,"[Star, Sunday star]",dlc_2isamu_ver01,[Washington],District of Columbia,[None],19490724,None,,1972,Daily,...,W.D. Wallach & Hope,,101,1854,[District of Columbia],"[Washington (D.C.)--fast--(OCoLC)fst01204505, ...",Evening star. [volume],evening star.,page,https://chroniclingamerica.loc.gov/lccn/sn8304...
2,[],iune_foxtrot_ver01,[Chicago],Illinois,[Cook County],19130312,None,,1917,Daily (except Sunday and holidays),...,N.D. Cochran,,26,1911,[Illinois],"[Chicago (Ill.)--Newspapers., Illinois--Chicag...",The day book. [volume],day book.,page,https://chroniclingamerica.loc.gov/lccn/sn8304...
3,[],iune_foxtrot_ver01,[Chicago],Illinois,[Cook County],19130405,None,FINAL EDITION,1917,Daily (except Sunday and holidays),...,N.D. Cochran,,32,1911,[Illinois],"[Chicago (Ill.)--Newspapers., Illinois--Chicag...",The day book. [volume],day book.,page,https://chroniclingamerica.loc.gov/lccn/sn8304...
4,[],uuml_hincapie_ver01,[Ogden],Utah,[Weber],19140606,None,4 P.M. City Edition,1920,Daily (except Sun.),...,W. Glasmann,MAGAZINE SECTION,14,1913,[Utah],"[Ogden (Utah)--Newspapers., Utah--Ogden.--fast...",The Ogden standard. [volume],ogden standard.,page,https://chroniclingamerica.loc.gov/lccn/sn8505...
5,[],iune_delta_ver01,[Chicago],Illinois,[Cook County],19130625,None,,1917,Daily (except Sunday and holidays),...,N.D. Cochran,,32,1911,[Illinois],"[Chicago (Ill.)--Newspapers., Illinois--Chicag...",The day book. [volume],day book.,page,https://chroniclingamerica.loc.gov/lccn/sn8304...
6,[],iune_foxtrot_ver01,[Chicago],Illinois,[Cook County],19130319,None,,1917,Daily (except Sunday and holidays),...,N.D. Cochran,,32,1911,[Illinois],"[Chicago (Ill.)--Newspapers., Illinois--Chicag...",The day book. [volume],day book.,page,https://chroniclingamerica.loc.gov/lccn/sn8304...
7,[],iune_foxtrot_ver01,[Chicago],Illinois,[Cook County],19130318,None,,1917,Daily (except Sunday and holidays),...,N.D. Cochran,,7,1911,[Illinois],"[Chicago (Ill.)--Newspapers., Illinois--Chicag...",The day book. [volume],day book.,page,https://chroniclingamerica.loc.gov/lccn/sn8304...
8,[],iune_foxtrot_ver01,[Chicago],Illinois,[Cook County],19130311,None,,1917,Daily (except Sunday and holidays),...,N.D. Cochran,,28,1911,[Illinois],"[Chicago (Ill.)--Newspapers., Illinois--Chicag...",The day book. [volume],day book.,page,https://chroniclingamerica.loc.gov/lccn/sn8304...
9,[],iune_delta_ver01,[Chicago],Illinois,[Cook County],19130918,None,,1917,Daily (except Sunday and holidays),...,N.D. Cochran,,7,1911,[Illinois],"[Chicago (Ill.)--Newspapers., Illinois--Chicag...",The day book. [volume],day book.,page,https://chroniclingamerica.loc.gov/lccn/sn8304...
10,[],iune_golf_ver01,[Chicago],Illinois,[Cook County],19140811,None,LAST EDITION,1917,Daily (except Sunday and holidays),...,N.D. Cochran,,12,1911,[Illinois],"[Chicago (Ill.)--Newspapers., Illinois--Chicag...",The day book. [volume],day book.,page,https://chroniclingamerica.loc.gov/lccn/sn8304...
11,[],iune_hotel_ver01,[Chicago],Illinois,[Cook County],19151006,None,LAST EDITION,1917,Daily (except Sunday and holidays),...,N.D. Cochran,,2,1911,[Illinois],"[Chicago (Ill.)--Newspapers., Illinois--Chicag...",The day book. [volume],day book.,page,https://chroniclingamerica.loc.gov/lccn/sn8304...
12,[],iune_echo_ver01,[Chicago],Illinois,[Cook County],19120305,None,,1917,Daily (except Sunday and holidays),...,N.D. Cochran,,26,1911,[Illinois],"[Chicago (Ill.)--Newspapers., Illinois--Chicag...",The day book. [volume],day book.,page,https://chroniclingamerica.loc.gov/lccn/sn8304...
13,"[Star, Sunday star]",dlc_1stella_ver01,[Washington],District of Columbia,[None],19410330,None,,1972,Daily,...,W.D. Wallach & Hope,,137,1854,[District of Columbia],"[Washington (D.C.)--fast--(OCoLC)fst01204505, ...",Evening star. [volume],evening star.,page,https://chroniclingamerica.loc.gov/lccn/sn8304...
14,[],mthi_beargrass_ver01,"[Fort Peck, Wheeler]",Montana,"[Valley, Valley]",19350502,None,,1939,Weekly,...,M.D. Eastly,,2,1934,"[Montana, Montana]",[],The Fort Peck press. [volume],fort peck press.,page,https://chroniclingamerica.loc.gov/lccn/sn8505...
15,[],iune_foxtrot_ver01,[Chicago],Illinois,[Cook County],19130129,None,,1917,Daily (except Sunday and holidays),...,N.D. Cochran,,2,1911,[Illinois],"[Chicago (Ill.)--Newspapers., Illinois--Chicag...",The day book. [volume],day book.,page,https://chroniclingamerica.loc.gov/lccn/sn8304...
16,[],iune_foxtrot_ver01,[Chicago],Illinois,[Cook County],19130310,None,,1917,Daily (except Sunday and holidays),...,N.D. Cochran,,32,1911,[Illinois],"[Chicago (Ill.)--Newspapers., Illinois--Chicag...",The day book. [volume],day book.,page,https://chroniclingamerica.loc.gov/lccn/sn8304...
17,[],iune_foxtrot_ver01,[Chicago],Illinois,[Cook County],19130315,None,FINAL EDITION,1917,Daily (except Sunday and holidays),...,N.D. Cochran,,32,1911,[Illinois],"[Chicago (Ill.)--Newspapers., Illinois--Chicag...",The day book. [volume],day book.,page,https://chroniclingamerica.loc.gov/lccn/sn8304...
18,[],iune_foxtrot_ver01,[Chicago],Illinois,[Cook County],19130728,None,,1917,Daily (except Sunday and holidays),...,N.D. Cochran,,3,1911,[Illinois],"[Chicago (Ill.)--Newspapers., Illinois--Chicag...",The day book. [volume],day book.,page,https://chroniclingamerica.loc.gov/lccn/sn8304...
19,[],iune_foxtrot_ver01,[Chicago],Illinois,[Cook County],19130724,None,,1917,Daily (except Sunday and holidays),...,N.D. Cochran,,5,1911,[Illinois],"[Chicago (Ill.)--Newspapers., Illinois--Chicag...",The day book. [volume],day book.,page,https://chroniclingamerica.loc.gov/lccn/sn8304...

# Exchange Rate Database Exercise

In [44]:
url = 'https://api.exchangeratesapi.io/latest?base=NOK'
r = requests.get(url)
r.json() #json is a dictionary
search_json = r.json()
search_json.keys() #looking at what columns there are

dict_keys(['rates', 'base', 'date'])

- **Q1: What is the average exchange rate value this search returns?**

In [56]:
a = round(pd.DataFrame(r.json()).describe(),3)
a

          rates
count    33.000
mean     51.898
std     258.408
min       0.082
25%       0.192
50%       0.735
75%       3.385
max    1485.699

- **Q2: Change the base to Euros, then tell me how many Japanese Yen is in a euro.**

In [70]:
#change base rate to EUR (euros)
url = 'https://api.exchangeratesapi.io/latest?base=EUR'
r = requests.get(url)
r.json() 
pd.DataFrame(r.json())
r.json()['rates']['JPY'] #to just get the value of the Yen

119.92

- **Q3: What was the number of Yen per Euro on Jan 2, 2018?**

In [68]:
#change base rate to EUR (euros) and filter just for  Jan 2, 2018
url = 'https://api.exchangeratesapi.io/history?start_at=2018-01-02&end_at=2018-01-02&base=EUR' #change LATEST to HISTORY
r = requests.get(url)
pd.DataFrame(r.json()) 
r.json()['rates']['2018-01-02']['JPY'] #to specify the exact date and Yen

135.35

- **Q4: Bonus, prof can show: Get a time series of EURJPY from 2018 through 2019.**

In [75]:
url = 'https://api.exchangeratesapi.io/history?start_at=2018-01-01&end_at=2019-12-31&base=EUR' #change LATEST to HISTORY
r = requests.get(url)
df = pd.DataFrame(r.json()) 
#how do we pull out a dictionary inside another variable?
df['EURJPY'] = df['rates'].apply(lambda x: x.get('JPY')) #create a EURJPY column
df

,rates,start_at,base,end_at,EURJPY
2018-01-02,"{'CAD': 1.5128, 'HKD': 9.4283, 'SGD': 1.6031, ...",2018-01-01,EUR,2019-12-31,135.35
2018-01-03,"{'CAD': 1.5047, 'HKD': 9.3985, 'SGD': 1.5988, ...",2018-01-01,EUR,2019-12-31,134.97
2018-01-04,"{'CAD': 1.5114, 'HKD': 9.4323, 'SGD': 1.6043, ...",2018-01-01,EUR,2019-12-31,135.92
2018-01-05,"{'CAD': 1.5068, 'HKD': 9.4188, 'SGD': 1.5993, ...",2018-01-01,EUR,2019-12-31,136.45
2018-01-08,"{'CAD': 1.488, 'HKD': 9.3656, 'SGD': 1.5956, '...",2018-01-01,EUR,2019-12-31,135.34
2018-01-09,"{'CAD': 1.4826, 'HKD': 9.3323, 'SGD': 1.5932, ...",2018-01-01,EUR,2019-12-31,134.31
2018-01-10,"{'CAD': 1.4931, 'HKD': 9.3809, 'SGD': 1.5981, ...",2018-01-01,EUR,2019-12-31,133.62
2018-01-11,"{'CAD': 1.5093, 'HKD': 9.4002, 'SGD': 1.6006, ...",2018-01-01,EUR,2019-12-31,134.19
2018-01-12,"{'CAD': 1.5194, 'HKD': 9.4962, 'SGD': 1.6103, ...",2018-01-01,EUR,2019-12-31,134.88
2018-01-15,"{'CAD': 1.5263, 'HKD': 9.605, 'SGD': 1.6223, '...",2018-01-01,EUR,2019-12-31,135.81
2018-01-16,"{'CAD': 1.5194, 'HKD': 9.568, 'SGD': 1.6185, '...",2018-01-01,EUR,2019-12-31,135.40
2018-01-17,"{'CAD': 1.5185, 'HKD': 9.5415, 'SGD': 1.6153, ...",2018-01-01,EUR,2019-12-31,135.21
2018-01-18,"{'CAD': 1.5229, 'HKD': 9.5648, 'SGD': 1.6175, ...",2018-01-01,EUR,2019-12-31,136.07
2018-01-19,"{'CAD': 1.5246, 'HKD': 9.5814, 'SGD': 1.6178, ...",2018-01-01,EUR,2019-12-31,135.54
2018-01-22,"{'CAD': 1.527, 'HKD': 9.5689, 'SGD': 1.6151, '...",2018-01-01,EUR,2019-12-31,135.66
2018-01-23,"{'CAD': 1.5289, 'HKD': 9.576, 'SGD': 1.6162, '...",2018-01-01,EUR,2019-12-31,135.35
2018-01-24,"{'CAD': 1.5229, 'HKD': 9.6556, 'SGD': 1.6181, ...",2018-01-01,EUR,2019-12-31,135.13
2018-01-25,"{'CAD': 1.5289, 'HKD': 9.6996, 'SGD': 1.6202, ...",2018-01-01,EUR,2019-12-31,135.12
2018-01-26,"{'CAD': 1.5325, 'HKD': 9.7222, 'SGD': 1.6259, ...",2018-01-01,EUR,2019-12-31,135.95
2018-01-29,"{'CAD': 1.5269, 'HKD': 9.6783, 'SGD': 1.622, '...",2018-01-01,EUR,2019-12-31,134.75
2018-01-30,"{'CAD': 1.5304, 'HKD': 9.7117, 'SGD': 1.628, '...",2018-01-01,EUR,2019-12-31,134.98
2018-01-31,"{'CAD': 1.529, 'HKD': 9.7413, 'SGD': 1.6288, '...",2018-01-01,EUR,2019-12-31,135.60
2018-02-01,"{'CAD': 1.5348, 'HKD': 9.7429, 'ISK': 125.01, ...",2018-01-01,EUR,2019-12-31,136.62
2018-02-02,"{'CAD': 1.5387, 'HKD': 9.7692, 'ISK': 125.2, '...",2018-01-01,EUR,2019-12-31,137.22
2018-02-05,"{'CAD': 1.5468, 'HKD': 9.7288, 'ISK': 125.0, '...",2018-01-01,EUR,2019-12-31,136.67
2018-02-06,"{'CAD': 1.5488, 'HKD': 9.6403, 'ISK': 125.0, '...",2018-01-01,EUR,2019-12-31,134.97
2018-02-07,"{'CAD': 1.5445, 'HKD': 9.6463, 'ISK': 125.0, '...",2018-01-01,EUR,2019-12-31,134.84
2018-02-08,"{'CAD': 1.5402, 'HKD': 9.5795, 'ISK': 125.2, '...",2018-01-01,EUR,2019-12-31,134.31
2018-02-09,"{'CAD': 1.5475, 'HKD': 9.5985, 'ISK': 125.2, '...",2018-01-01,EUR,2019-12-31,133.59
2018-02-12,"{'CAD': 1.5427, 'HKD': 9.5892, 'ISK': 125.4, '...",2018-01-01,EUR,2019-12-31,133.23
...,...,...,...,...,...
2019-11-18,"{'CAD': 1.4622, 'HKD': 8.6593, 'ISK': 135.9, '...",2018-01-01,EUR,2019-12-31,120.55
2019-11-19,"{'CAD': 1.4633, 'HKD': 8.6709, 'ISK': 136.3, '...",2018-01-01,EUR,2019-12-31,120.46
2019-11-20,"{'CAD': 1.4711, 'HKD': 8.6549, 'ISK': 135.9, '...",2018-01-01,EUR,2019-12-31,119.96
2019-11-21,"{'CAD': 1.4759, 'HKD': 8.6739, 'ISK': 136.3, '...",2018-01-01,EUR,2019-12-31,120.46
2019-11-22,"{'CAD': 1.4679, 'HKD': 8.6525, 'ISK': 136.3, '...",2018-01-01,EUR,2019-12-31,120.03
2019-11-25,"{'CAD': 1.4648, 'HKD': 8.6164, 'ISK': 135.9, '...",2018-01-01,EUR,2019-12-31,119.88
2019-11-26,"{'CAD': 1.4663, 'HKD': 8.6256, 'ISK': 135.4, '...",2018-01-01,EUR,2019-12-31,120.09
2019-11-27,"{'CAD': 1.4605, 'HKD': 8.6176, 'ISK': 135.0, '...",2018-01-01,EUR,2019-12-31,120.18
2019-11-28,"{'CAD': 1.4625, 'HKD': 8.6136, 'ISK': 135.0, '...",2018-01-01,EUR,2019-12-31,120.50
2019-11-29,"{'CAD': 1.4614, 'HKD': 8.5954, 'ISK': 134.0, '...",2018-01-01,EUR,2019-12-31,120.43
2019-12-02,"{'CAD': 1.4656, 'HKD': 8.6297, 'ISK': 134.8, '...",2018-01-01,EUR,2019-12-31,120.75
2019-12-03,"{'CAD': 1.4747, 'HKD': 8.6675, 'ISK': 134.4, '...",2018-01-01,EUR,2019-12-31,120.39
2019-12-04,"{'CAD': 1.4707, 'HKD': 8.6753, 'ISK': 134.2, '...",2018-01-01,EUR,2019-12-31,120.45
2019-12-05,"{'CAD': 1.461, 'HKD': 8.6853, 'ISK': 134.4, 'P...",2018-01-01,EUR,2019-12-31,120.69
2019-12-06,"{'CAD': 1.4618, 'HKD': 8.6852, 'ISK': 134.6, '...",2018-01-01,EUR,2019-12-31,120.44
2019-12-09,"{'CAD': 1.4675, 'HKD': 8.6692, 'ISK': 134.3, '...",2018-01-01,EUR,2019-12-31,120.15
2019-12-10,"{'CAD': 1.4666, 'HKD': 8.6691, 'ISK': 134.7, '...",2018-01-01,EUR,2019-12-31,120.27
2019-12-11,"{'CAD': 1.4661, 'HKD': 8.6538, 'ISK': 135.1, '...",2018-01-01,EUR,2019-12-31,120.44
2019-12-12,"{'CAD': 1.4676, 'HKD': 8.6923, 'ISK': 136.7, '...",2018-01-01,EUR,2019-12-31,120.95
2019-12-13,"{'CAD': 1.4712, 'HKD': 8.7062, 'ISK': 137.0, '...",2018-01-01,EUR,2019-12-31,122.43
2019-12-16,"{'CAD': 1.4621, 'HKD': 8.6856, 'ISK': 136.8, '...",2018-01-01,EUR,2019-12-31,121.97
2019-12-17,"{'CAD': 1.469, 'HKD': 8.6953, 'ISK': 136.6, 'P...",2018-01-01,EUR,2019-12-31,122.31
2019-12-18,"{'CAD': 1.4624, 'HKD': 8.6566, 'ISK': 137.2, '...",2018-01-01,EUR,2019-12-31,121.81
2019-12-19,"{'CAD': 1.4588, 'HKD': 8.6687, 'ISK': 137.2, '...",2018-01-01,EUR,2019-12-31,121.73
2019-12-20,"{'CAD': 1.4579, 'HKD': 8.6511, 'ISK': 136.4, '...",2018-01-01,EUR,2019-12-31,121.31
2019-12-23,"{'CAD': 1.4577, 'HKD': 8.6232, 'ISK': 135.4, '...",2018-01-01,EUR,2019-12-31,121.18
2019-12-24,"{'CAD': 1.4582, 'HKD': 8.629, 'ISK': 135.6, 'P...",2018-01-01,EUR,2019-12-31,121.19
2019-12-27,"{'CAD': 1.4592, 'HKD': 8.6845, 'ISK': 135.6, '...",2018-01-01,EUR,2019-12-31,122.23
2019-12-30,"{'CAD': 1.4621, 'HKD': 8.7133, 'ISK': 135.8, '...",2018-01-01,EUR,2019-12-31,122.19
2019-12-31,"{'CAD': 1.4598, 'HKD': 8.7473, 'ISK': 135.8, '...",2018-01-01,EUR,2019-12-31,121.94